name: Test & compile

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: 'npm'
    - run: npm ci
    - run: npm test
    - run: npm run build --if-present
    - uses: actions/upload-artifact@v2
      with:
        name: transpiled
        path: "."
